repos:
  - repo: local
    hooks:
      - id: system
        name: Black
        entry: poetry run black . --config=pyproject.toml
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: isort
        entry: poetry run isort . --sp=pyproject.toml
        pass_filenames: false
        language: system
  - repo: local
    hooks:
      - id: system
        name: flake8
        entry: poetry run flake8 . --config=.flake8
        pass_filenames: false
        language: system
